name: Heroku Workflow

on:
  push:
    branches:
    - master


jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pip install pytest
        pytest tests

  Deploy:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Login to Heroku
      id: login
      uses: actions/heroku@master
      with:
        args: "container:login"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Push to Heroku
      uses: actions/heroku@master
      with:
        args: "container:push web -a \"$HEROKU_APP\""
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: tsds-streamlit-nn-intuition
    - name: Release to Heroku
      uses: actions/heroku@master
      with:
        args: "container:release web -a \"$HEROKU_APP\""
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: tsds-streamlit-nn-intuition